name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # Altere para "master" se a sua branch principal tiver esse nome
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: //://
      
